# Generated by Django 6.0.3 on 2026-03-16 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('APPARTEMENT', 'Appartement'), ('VILLA', 'Villa'), ('TERRAIN', 'Terrain'), ('COMMERCIAL', 'Local commercial'), ('AUTRE', 'Autre')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Type de bien',
                'verbose_name_plural': 'Types de bien',
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartiers', to='api.ville')),
            ],
            options={
                'verbose_name': 'Quartier',
                'verbose_name_plural': 'Quartiers',
                'ordering': ['ville', 'nom'],
                'unique_together': {('nom', 'ville')},
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original', models.CharField(blank=True, max_length=50, null=True)),
                ('titre', models.CharField(max_length=500)),
                ('type_operation', models.CharField(blank=True, choices=[('VENTE', 'Vente'), ('LOCATION', 'Location'), ('LOCATION_MEUBLEE', 'Location meublée')], max_length=20)),
                ('prix_fcfa', models.BigIntegerField()),
                ('prix_m2_fcfa', models.BigIntegerField(blank=True, null=True)),
                ('tranche_prix', models.CharField(blank=True, max_length=50)),
                ('surface_m2', models.FloatField(blank=True, null=True)),
                ('nb_chambres', models.IntegerField(blank=True, null=True)),
                ('nb_salons', models.IntegerField(blank=True, null=True)),
                ('nb_sdb', models.IntegerField(blank=True, null=True)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('annee_pub', models.IntegerField(blank=True, null=True)),
                ('mois_pub', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('date_scraping', models.DateTimeField(auto_now_add=True)),
                ('quartier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.quartier')),
                ('type_bien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.typebien')),
                ('ville', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ville')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-date_publication'],
                'indexes': [models.Index(fields=['ville', 'quartier'], name='api_annonce_ville_i_50b949_idx'), models.Index(fields=['prix_fcfa'], name='api_annonce_prix_fc_68d159_idx'), models.Index(fields=['date_publication'], name='api_annonce_date_pu_e5aab1_idx')],
            },
        ),
    ]
